### PR TITLE
Describe how to pass options to postcss-sorting

### PR DESCRIPTION
**Pull request by Wilfred**
It's not very clear how to pass options, especially when using the CLI. Take the information in #5 and add it to the readme.

### CODE REVIEW

**Comment by hudochenkov** [comment]
It's not clear how to use postcss-sorting with PostCSS CLI with this PR either. “Options” section is for options descriptions only. There is “Usage” section in readme, where you can add subsection (like it did for Gulp/Grunt) for PostCSS CLI (what is config looks like for postcss-sorting and how to run it).

**Comment by BartKrol** [comment]
Hey. I'm trying to clean my scss files using `postcss-sorting` and I cannot make it work. I was looking at the README, but this PR is the closet thing with an explanation how to use it via CLI.

I'm trying to use it in a following way:
`postcss -s postcss-scss -r app/**/*.scss --no-map -c .postcssrc.json - postcss-sorting`
but it seems like it's not using anything in the config and properties are not being sorted. 

My `.postcssrc.json` file is copied from here https://gist.github.com/hudochenkov/b7127590d3013a5982ed90ad63a85306#file-default-json

**Comment by hudochenkov** [comment]
@BartKrol looks like you can't configure PostCSS CLI properly. Refer to its docs, please.

**Comment by andrewkendall** [comment]
@BartKrol did you ever figure out how to get this to work?

I've been going on the assumption that something like `postcss test.css --use postcss-sorting --config postcss-sorting.json --no-map` would work using the same config file you referenced, but I'm seeing no changes to the order of test.css on output :(

Would really appreciate a clear example of how the CLI should look and what exactly should be in the config file. I'm new to postcss-sorting trying to migrate from CSScomb so not sure if I'm missing some fundamentals on how the tool should work.

**Pull request closed without merging**
