### PR TITLE
at-variables config for Less

### PR DESCRIPTION
**Pull request by DarkPreacher**

### CODE REVIEW

**Comment by hudochenkov** [comment]
Thank you for your PR.

I see linting errors in Travis. I must have skipped precommit hook. Please run `npm run fix` to fix lint error. It will reformat files. It's ok.

Tests are missing. Please, add new keyword to https://github.com/hudochenkov/postcss-sorting/blob/3e0e8191699069866628458ad26c6483e363fc0a/lib/order/__tests__/order.js#L29

And add test cases to [keywords.css](https://github.com/hudochenkov/postcss-sorting/blob/master/lib/order/__tests__/fixtures/keywords.css) (it's an input) and [keywords.expected.css](https://github.com/hudochenkov/postcss-sorting/blob/master/lib/order/__tests__/fixtures/keywords.expected.css) (it's an expected output after running plugin with options defined in `__tests__/order.js`).

**Comment by DarkPreacher** [comment]
I've did `npm run fix` — it didn't change anything,
Keyword to `__tests__/order.js` I've added before, but missed test cases — fixed.

**Comment by hudochenkov** [comment]
> I've did `npm run fix` — it didn't change anything,

Weird. Just run it in your repository and it did change files. Could you try to delete `node_modules` and reinstall them, please? If it won't work, then I'll commit fix in your repository.

**Comment by DarkPreacher** [comment]
Had to run `npm run fix` under Ubuntu in VM, worked fine.
Have no idea why it don't do anything under Win10 with Node 9.

**Comment by hudochenkov** [comment]
Thank you!

**Pull request merged**
